<html>
<head>
    <title>Index</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>
<body>


<h1>Students</h1>
<table class="tbl-qa">
    <thead>
    <tr>
        <th class="table-header">Name</th>
        <th class="table-header">Surname</th>
        <th class="table-header">Email</th>
        <th class="table-header">Photo Link</th>
        <th class="table-header">Course</th>
        <th class="table-header">Actions</th>
    </tr>
    </thead>
    <tbody id="table-body">
    <?php
    if (!empty($students)) {
        foreach ($students as $student) {
            ?>
            <tr class="table-row" id="table-row-<?php echo $student["student_id"]; ?>">
                <td contenteditable="true" onBlur="saveToDatabase(this,'name','<?php echo $student["student_id"]; ?>')"
                    onClick="editRow(this);"><?php echo $student["name"]; ?></td>
                <td contenteditable="true"
                    onBlur="saveToDatabase(this,'surname','<?php echo $student["student_id"]; ?>')"
                    onClick="editRow(this);"><?php echo $student["surname"]; ?></td>
                <td contenteditable="true" onBlur="saveToDatabase(this,'email','<?php echo $student["student_id"]; ?>')"
                    onClick="editRow(this);"><?php echo $student["email"]; ?></td>
                <td><?php echo $student["photo"]; ?></td>
                <td contenteditable="true"
                    onBlur="saveToDatabase(this,'course_id','<?php echo $student["student_id"]; ?>')"
                    onClick="editRow(this);">
                    <?php if (!empty ($courses)): ?>
                        <select name="course_id">
                            <?php foreach ($courses as $course): ?>
                                <option value= <?= $course['course_id']; ?>
                                        <?php if ($course['course_id'] === $student["course_id"]) {
                                            echo 'selected';
                                        }
                                        ?>
                                ><?= $course['course']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    <?php endif; ?>
                </td>
                <td>
                    <button
                        onclick="deleteRecord(<?php echo $student["student_id"]; ?>);">Delete
                    </button>
                </td>
            </tr>
            <?php
        }
    }
    ?>
    </tbody>
</table>
<form id="student_form" enctype="multipart/form-data" action="/save/students/" method="POST">
    <input type="hidden" name="id" type="text"/>
    <input name="name" required type="text"/>
    <input name="surname" required type="text"/>
    <input name="email" required type="email"/>
    <input type="hidden" name="MAX_FILE_SIZE" value="300000000"/>
    <input name="userfile" type="file" accept="image/jpeg,image/png">
    <?php if (!empty ($courses)): ?>
        <select name="course_id">
            <option value=""> Please select...</option>
            <?php foreach ($courses as $course): ?>
                <option value= <?= $course['course_id']; ?>><?= $course['course']; ?></option>
            <?php endforeach; ?>
        </select>
    <?php endif; ?>
    <input type="submit" value="Save"/>

</form>
<script>
    function saveToDatabase(editableObj, column, student_id) {
        $(editableObj).css("background", "#FFF url(loaderIcon.gif) no-repeat right");
        $.ajax({
            url: "/edit/students/",
            type: "POST",
            data: 'column=' + column + '&editval=' + $(editableObj).text() + '&student_id=' + student_id,
            success: function (data) {
                $(editableObj).css("background", "#FDFDFD");
            }
        });
    }
    function deleteRecord(student_id) {
        if (confirm("Are you sure you want to delete this row?")) {
            $.ajax({
                url: "/delete/students/",
                type: "POST",
                data: 'student_id=' + student_id,
                success: function (data) {
                    $("#table-row-" + student_id).remove();
                }
            });
        }
    }
</script>
</body>
</html>
